In [1]:
class Student:
    def __init__(self, name):
        self.name = name
        self.marks = []

    def enterMarks(self):
        for i in range(3):
            m = int(input(f"Enter the marks for subject {i+1}: "))
            self.marks.append(m)
            

    def display(self):
        print(f"{self.name} got {self.marks}")

    def average(self):
        return sum(self.marks) / len(self.marks)

n = int(input("Enter the number of students: "))

for i in range(n):
    print(f"\nEnter the details of student {i+1}")
    name = input("Enter the name of Student: ")
    s = Student(name)
    s.enterMarks()
    print(f"\nDetails of Student {i+1} are:")
    s.display()
    print(f"Average marks: {s.average()}\n")


KeyboardInterrupt: Interrupted by user

In [3]:
# List


# Creating a list
my_list = [1, 2, 3, 4, 5]

# 1. append() - Adds an element to the end of the list
my_list.append(6)
print("After append(6):", my_list)

# 2. extend() - Adds multiple elements to the end of the list
my_list.extend([7, 8, 9])
print("After extend([7, 8, 9]):", my_list)

# 3. insert() - Inserts an element at a specified position
my_list.insert(0, 5)  # Insert 0 at index 0
print("After insert(0, 0):", my_list)

# 4. remove() - Removes the first occurrence of a specified value
my_list.remove(3)
print("After remove(3):", my_list)

# 5. pop() - Removes and returns the element at the specified position
popped_value = my_list.pop(2)  # Pop the element at index 2
print("Popped value:", popped_value)
print("After pop(2):", my_list)

# 6. index() - Returns the index of the first occurrence of a specified value
index_of_5 = my_list.index(5)
print("Index of 5:", index_of_5)

# 7. count() - Returns the number of occurrences of a specified value
count_of_1 = my_list.count(1)
print("Count of 1:", count_of_1)

# 8. sort() - Sorts the list in ascending order
my_list.sort()
print("After sort():", my_list)

# 9. min() - Finds the minimum value in the list
min_value = min(my_list)
print("Minimum value:", min_value)

# 10. max() - Finds the maximum value in the list
max_value = max(my_list)
print("Maximum value:", max_value)

# 11. reverse() - Reverses the order of the list
my_list.reverse()
print("After reverse():", my_list)

# 12. clear() - Removes all elements from the list
my_list.clear()
print("After clear():", my_list)

After append(6): [1, 2, 3, 4, 5, 6]
After extend([7, 8, 9]): [1, 2, 3, 4, 5, 6, 7, 8, 9]
After insert(0, 0): [5, 1, 2, 3, 4, 5, 6, 7, 8, 9]
After remove(3): [5, 1, 2, 4, 5, 6, 7, 8, 9]
Popped value: 2
After pop(2): [5, 1, 4, 5, 6, 7, 8, 9]
Index of 5: 0
Count of 1: 1
After sort(): [1, 4, 5, 5, 6, 7, 8, 9]
After reverse(): [9, 8, 7, 6, 5, 5, 4, 1]
After clear(): []


In [12]:
 # read postive and negative numeber in list 

n = int(input("Enter the number "))
ol=[]
nl=[]
pl=[]
for i in range (n):
    e = int(input("Enter the elements"))
    ol.append(e)
for i in range(len(ol)):
    if ol[i] >= 0:
        pl.append(ol[i])
    else:
        nl.append(ol[i])

print(nl)
print(pl)


Enter the number  4
Enter the elements -32
Enter the elements -43
Enter the elements 34
Enter the elements 54


[-32, -43]
[34, 54]


In [16]:
# reverse without creating new list

def reverse(l):
    l.reverse()
    return(l)
n = int(input("size of list"))
ol=[]
for i in range(n):
    e=int(input("enter the elements ="))
    ol.append(e)
print("original list", ol)
n=reverse(ol)
print("list after reverse",n)

size of list 4
enter the elements = 5
enter the elements = 4
enter the elements = 3
enter the elements = 23


original list [5, 4, 3, 23]
list after reverse [23, 3, 4, 5]


In [21]:
# Demonstrating various dictionary methods in Python

# Creating a dictionary
my_dict = {
    'name': 'Alice',
    'age': 30,
    'city': 'New York'
}

# Display the original dictionary
print("Original dictionary:", my_dict)

# 1. get() - Retrieves the value for a specified key
name = my_dict.get('name')
print("Value of 'name':", name)

# 2. keys() - Returns a view object that displays a list of all the keys
keys = my_dict.keys()
print("Keys in the dictionary:", keys)

# 3. values() - Returns a view object that displays a list of all the values
values = my_dict.values()
print("Values in the dictionary:", values)

# 4. items() - Returns a view object that displays a list of the dictionary's key-value pairs
items = my_dict.items()
print("Key-Value pairs in the dictionary:", items)

# 5. update() - Updates the dictionary with elements from another dictionary or iterable
my_dict.update({'age': 31, 'country': 'USA'})
print("After update():", my_dict)

del my_dict['country']
print(my_dict)  

# 6. pop() - Removes the specified key and returns its value
popped_value = my_dict.pop('city')
print("Popped value for 'city':", popped_value)
print("After pop('city'):", my_dict)

# 7. popitem() - Removes and returns the last inserted key-value pair as a tuple
last_item = my_dict.popitem()
print("Popped last item:", last_item)
print("After popitem():", my_dict)



# 8. clear() - Removes all items from the dictionary
my_dict.clear()
print("After clear():", my_dict)

# 9. copy() - Returns a shallow copy of the dictionary
my_dict = {'name': 'Alice', 'age': 30}
copy_dict = my_dict.copy()
print("Original dictionary:", my_dict)
print("Copied dictionary:", copy_dict)



Original dictionary: {'name': 'Alice', 'age': 30, 'city': 'New York'}
Value of 'name': Alice
Keys in the dictionary: dict_keys(['name', 'age', 'city'])
Values in the dictionary: dict_values(['Alice', 30, 'New York'])
Key-Value pairs in the dictionary: dict_items([('name', 'Alice'), ('age', 30), ('city', 'New York')])
After update(): {'name': 'Alice', 'age': 31, 'city': 'New York', 'country': 'USA'}
{'name': 'Alice', 'age': 31, 'city': 'New York'}
Popped value for 'city': New York
After pop('city'): {'name': 'Alice', 'age': 31}
Popped last item: ('age', 31)
After popitem(): {'name': 'Alice'}
After clear(): {}
Original dictionary: {'name': 'Alice', 'age': 30}
Copied dictionary: {'name': 'Alice', 'age': 30}


In [ ]:
# dictionary in list 

# Creating an initial list
my_list = [1, 2, 3]

# 1. append() - Adds an element to the end of the list
my_list.append(4)
print("After append(4):", my_list)

# 2. extend() - Adds multiple elements to the end of the list
my_list.extend([5, 6])
print("After extend([5, 6]):", my_list)

# 3. reverse() - Reverses the order of the list
my_list.reverse()
print("After reverse():", my_list)

# 4. pop() - Removes and returns the element at the specified position (last by default)
popped_value = my_list.pop()  # Popping the last element
print("Popped value:", popped_value)
print("After pop():", my_list)

# 5. remove() - Removes the first occurrence of a specified value
my_list.remove(2)
print("After remove(2):", my_list)

# 6. copy() - Returns a shallow copy of the list
copied_list = my_list.copy()
print("Copied list:", copied_list)

# 7. Adding more elements for demonstration
my_list.append(7)
my_list.append(8)
print("After adding 7 and 8:", my_list)

# 8. Reverse the copied list
copied_list.reverse()
print("Reversed copied list:", copied_list)

# Final output of both lists
print("Final my_list:", my_list)
print("Final copied_list:", copied_list)

In [23]:
# count frequency of character repeated in string

word=input("enter word")
dict={}
for i in word:
    if i in dict:
        dict[i]+=1
    else:
        dict[i]=1
print(str(dict))

enter word suhas


{'s': 2, 'u': 1, 'h': 1, 'a': 1}


In [24]:
# Set methods

my_set = {1, 2, 3, 4, 5}
print("Original set:", my_set)

# 1. add() - Adds an element to the set
my_set.add(6)
print("After add(6):", my_set)

# 2. update() - Adds multiple elements to the set
my_set.update([7, 8, 9])
print("After update([7, 8, 9]):", my_set)

# 3. remove() - Removes a specified element; raises KeyError if not found
my_set.remove(4)
print("After remove(4):", my_set)

# 4. discard() - Removes a specified element; does not raise an error if not found
my_set.discard(10)  # No error, since 10 is not in the set
print("After discard(10):", my_set)

# 5. pop() - Removes and returns an arbitrary element from the set
popped_value = my_set.pop()  # Random element removed
print("Popped value:", popped_value)
print("After pop():", my_set)

# 6. clear() - Removes all elements from the set
my_set.clear()
print("After clear():", my_set)

# 7. Creating another set for demonstration
another_set = {3, 4, 5, 6, 7}

# 8. union() - Returns a new set with elements from both sets
union_set = my_set.union(another_set)
print("Union of my_set and another_set:", union_set)

# 9. intersection() - Returns a new set with elements common to both sets
intersection_set = my_set.intersection(another_set)
print("Intersection of my_set and another_set:", intersection_set)

# 10. difference() - Returns a new set with elements in the first set but not in the second
difference_set = another_set.difference(my_set)
print("Difference of another_set - my_set:", difference_set)

Original set: {1, 2, 3, 4, 5}
After add(6): {1, 2, 3, 4, 5, 6}
After update([7, 8, 9]): {1, 2, 3, 4, 5, 6, 7, 8, 9}
After remove(4): {1, 2, 3, 5, 6, 7, 8, 9}
After discard(10): {1, 2, 3, 5, 6, 7, 8, 9}
Popped value: 1
After pop(): {2, 3, 5, 6, 7, 8, 9}
After clear(): set()
Union of my_set and another_set: {3, 4, 5, 6, 7}
Intersection of my_set and another_set: set()
Difference of another_set - my_set: {3, 4, 5, 6, 7}


In [29]:
# Tuples 

my_tuple = (1, 2, 3, 1, 1, 4, 5)

# length
print(len(my_tuple))

print(my_tuple.count(1))

print(my_tuple.index(3))

print(my_tuple[1])

7
3
2
2


In [35]:
class Faculty:
    def __init__(self, id=None, name=None, salary=None):
        self.id = id
        self.name = name
        self.salary = salary

    def getdata(self):
        self.id = input("Enter faculty ID: ")
        self.name = input("Enter faculty name: ")
        self.salary = input("Enter faculty salary: ")

    def putdata(self):
        print("Faculty ID:", self.id)
        print("Faculty Name:", self.name)
        print("Faculty Salary:", self.salary)

# Create an instance of the Faculty class
faculty = Faculty()

# Call the methods to get and put data
faculty.getdata()
faculty.putdata()

Enter faculty ID:  34
Enter faculty name:  suhas
Enter faculty salary:  343434


Faculty ID: 34
Faculty Name: suhas
Faculty Salary: 343434


In [43]:
# Using a NumPy module create an array
# and check the following:
# 1. Type of array 2. Axes of array 3. Shape
# of array 4. Type of elements in array

import numpy as np

array = np.array([[1, 2, 3], [4, 5, 6]])

print("Type of array:", type(array))
print("Number of axes (dimensions) of array:", array.ndim)
print("Shape of array:",array.shape)
print(array.size)
print("Type of elements in array:",array.dtype)


Type of array: <class 'numpy.ndarray'>
Number of axes (dimensions) of array: 2
Shape of array: (2, 3)
6
int64
Type of elements in array: int64


In [45]:
# Using a NumPy module create array and
# check the following:
# 1.Reshape 2*2*3 array
# 2. Sequence of integer from 0 to 30 with steps of 5
# 3. Flatten array


import numpy as np

# 1. Create a 2*2*3 array and reshape it
original_array = np.array([[[1, 2, 3], [4, 5, 6]], 
                            [[7, 8, 9], [10, 11, 12]]])
reshaped_array = original_array.reshape(2, 2, 3)
print("Reshaped Array (2*2*3):")
print(reshaped_array)

# 2. Create a sequence of integers from 0 to 30 with steps of 5
sequence_array = np.arange(0, 31, 5)
print("\nSequence of integers from 0 to 30 with steps of 5:")
print(sequence_array)

# 3. Flatten the reshaped array
flattened_array = reshaped_array.flatten()
print("\nFlattened Array:")
print(flattened_array)

zeros_array = np.zeros((2, 2, 3))
print("\nArray of zeros (2*2*3):")
print(zeros_array)

Reshaped Array (2*2*3):
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

Sequence of integers from 0 to 30 with steps of 5:
[ 0  5 10 15 20 25 30]

Flattened Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12]

Array of zeros (2*2*3):
[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


In [ ]:
# numpy built in methods 

import numpy as np

# 1. Create a NumPy array
array = np.array([[1, 2, 3], [4, 5, 6]])

# 2. Display the original array
print("Original Array:")
print(array)

# 3. Reshape the array
reshaped_array = array.reshape(3, 2)
print("\nReshaped Array (3x2):")
print(reshaped_array)

# 4. Create a zeros array
zeros_array = np.zeros((2, 3))
print("\nArray of Zeros (2x3):")
print(zeros_array)

# 5. Create an array of ones
ones_array = np.ones((2, 3))
print("\nArray of Ones (2x3):")
print(ones_array)

# 6. Create a range of values
range_array = np.arange(0, 10, 2)  # Start, Stop, Step
print("\nArray with a range of values (0 to 10 with step of 2):")
print(range_array)

# 7. Create an array of evenly spaced numbers
linspace_array = np.linspace(0, 1, 5)  # Start, Stop, Number of points
print("\nArray of evenly spaced numbers between 0 and 1 (5 points):")
print(linspace_array)

# 8. Flatten the array
flattened_array = array.flatten()
print("\nFlattened Array:")
print(flattened_array)

# 9. Sum of elements
sum_of_elements = np.sum(array)
print("\nSum of all elements in the original array:")
print(sum_of_elements)

# 10. Mean of elements
mean_of_elements = np.mean(array)
print("\nMean of all elements in the original array:")
print(mean_of_elements)

# 11. Maximum value
max_value = np.max(array)
print("\nMaximum value in the original array:")
print(max_value)

# 12. Minimum value
min_value = np.min(array)
print("\nMinimum value in the original array:")
print(min_value)

# 13. Transpose the array
transposed_array = np.transpose(array)
print("\nTransposed Array:")
print(transposed_array)

In [46]:
# .dot multi

import numpy as np
A = np.array([[1, 0, 0],
              [0, 0, 3],
              [4, 0, 0]])

B = np.array([[0, 5],
              [6, 0],
              [0, 7]])

result = A.dot(B)
print(result)

[[ 0  5]
 [ 0 21]
 [ 0 20]]


In [56]:
# matrix multiplication

import numpy as np


R = int(input("Enter the number of rows for the first matrix: "))
C = int(input("Enter the number of columns for the first matrix: "))
matrix1 = []
for i in range(R):
    a = []
    for j in range(C):
        a.append(int(input(f"Enter element ({i}, {j}): ")))
    matrix1.append(a) 

m = np.array(matrix1) 
print("First Matrix:")
print(m)

R1 = int(input("Enter the number of rows for the second matrix: "))
C1 = int(input("Enter the number of columns for the second matrix: "))
matrix2 = []
for i in range(R1):
    a = []
    for j in range(C1):
        a.append(int(input(f"Enter element ({i}, {j}): ")))
    matrix2.append(a) 
n = np.array(matrix2)
print("Second Matrix:")
print(n)


result = np.dot(m1, n)
print("Result of multiplication:")
print(result)

print("Transpose of the result:")
print(result.T)



Enter the number of rows for the first matrix:  2
Enter the number of columns for the first matrix:  3
Enter element (0, 0):  1
Enter element (0, 1):  2
Enter element (0, 2):  3
Enter element (1, 0):  4
Enter element (1, 1):  5
Enter element (1, 2):  6


First Matrix:
[[1 2 3]
 [4 5 6]]


Enter the number of rows for the second matrix:  3
Enter the number of columns for the second matrix:  2
Enter element (0, 0):  1
Enter element (0, 1):  2
Enter element (1, 0):  3
Enter element (1, 1):  4
Enter element (2, 0):  5
Enter element (2, 1):  6


Second Matrix:
[[1 2]
 [3 4]
 [5 6]]
Result of multiplication:
[[22 28]
 [49 64]]
Transpose of the result:
[[22 49]
 [28 64]]


In [60]:
# hstack vstack dstack concat

import numpy as np

# Creating two 2D arrays
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

# Horizontal stacking
hstacked = np.hstack((array1, array2))
print("Horizontal Stack:")
print(hstacked)

# Vertical stacking
vstacked = np.vstack((array1, array2))
print("\nVertical Stack:")
print(vstacked)

# Depth stacking
dstacked = np.dstack((array1, array2))
print("\nDepth Stack:")
print(dstacked)

# Concatenating along axis 0 (vertical)
concatenated = np.concatenate((array1, array2), axis=0)
print("\nConcatenate along axis 0:")
print(concatenated_axis0)


Horizontal Stack:
[[1 2 5 6]
 [3 4 7 8]]

Vertical Stack:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Depth Stack:
[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]

Concatenate along axis 0:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [64]:
# hsplit vsplit

arr=np.arange(16).reshape(4,4)
result1=np.hsplit(arr,2)
result2=np.vsplit(arr,2)
result3=np.array_split(arr,4)
print(result1)
print(result2)
print(result3)

[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])]


In [3]:
import numpy as np
import pandas as pd
data = pd.read_csv("/home/suhasext/Downloads/student-dataset.csv")
df= pd.DataFrame(data)
print(df)
print(df.head())
print(df.tail())
print(df.info())
print(df.describe())
print(df.loc[0:4,['Name','percentage']])
print(df.iloc[1:4])
print(df['Persentage'],dropna())
print(df['Persentage'],fillna(40))
print(df.columns)
df.to_csv('x.csv')






      id               name               nationality                 city  \
0      0          Kiana Lor                     China               Suzhou   
1      1     Joshua Lonaker  United States of America        Santa Clarita   
2      2      Dakota Blanco  United States of America              Oakland   
3      3    Natasha Yarusso  United States of America        Castro Valley   
4      4     Brooke Cazares                    Brazil  São José dos Campos   
..   ...                ...                       ...                  ...   
302  302        Austin Haas  United States of America             Columbus   
303  303    Madison Fithian  United States of America          Los Angeles   
304  304  Zachary Mulvahill  United States of America          Los Angeles   
305  305   Eliana Michelsen  United States of America              Oakland   
306  306    Dane Whittemore                    Canada              Toronto   

     latitude  longitude gender  ethnic.group  age  english.gra

KeyError: "None of [Index(['Name', 'percentage'], dtype='object')] are in the [columns]"